### ISSUE TITLE
Resources are not copied when installing the package

### ISSUE THREAD

**Issue by abdullah-alnahas** [obulat/trLemmer#2]
Hello,
I have installed your package using
`python setup.py install`
no errors, the installation is getting completed successfully. However, when using it, I am getting the following error:
`FileNotFoundError: [Errno 2] No such file or directory: '/path/to/python3.7/site-packages/trLemmer-0.1.0-py3.7.egg/trLemmer/resources/tr/phonetics/turkish-letter-names.txt`
So, I copied the resources by hand and it works. I guess it would be better to copy them while installing the package.

Thanks.

**Comment by obulat** [comment]
Thank you for creating the issue! I will resolve it shortly.

**Comment by obulat** [comment]
The latest commit should solve this issue. I also added nltk to dependencies in setup.py.

**Comment by abdullah-alnahas** [comment]
Thanks! It works for me now.
